<?php
defined('_JEXEC') or die('Restricted access');

use Joomla\CMS\Factory;
use Joomla\CMS\MVC\Model\BaseDatabaseModel;
use Joomla\CMS\MVC\Model\ListModel;

// Registering Helper
// Callable through BeersHelper::function() (is this case)
JLoader::register('BeersHelper', JPATH_ADMINISTRATOR . '/components/com_beers/helpers/beers.php');

class BeersModelBeers extends ListModel
{
	protected function _getListQuery()
	{
		$db = Factory::getDbo();

		$query = $db->getQuery(true);

		$query
			->select('*')
			->from($db->quoteName('#__beers'));

		return $query; // TODO: Change the autogenerated stub
	}

	public function import()
	{
		$data  = BeersHelper::orderBeers();
		$model = BaseDatabaseModel::getInstance('Beer', 'BeersModel', ['ignore_request' => true]);

		foreach ($data as $beer)
		{
			$model->save((array) $beer);
		}
	}
}