<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_banners
 *
 * @copyright   Copyright (C) 2005 - 2020 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

use Joomla\Utilities\ArrayHelper;

/**
 * Banners list controller class.
 *
 * @since  1.6
 */
class BeersControllerBeers extends JControllerAdmin
{
    /**
     * The prefix to use with controller messages.
     *
     * @var    string
     * @since  1.6
     */
    protected $text_prefix = 'COM_BEERS_BEERS';

    /**
     * Constructor.
     *
     * @param   array  $config  An optional associative array of configuration settings.
     *
     * @see     JControllerLegacy
     * @since   1.6
     */
    public function __construct($config = array())
    {
        parent::__construct($config);
    }

    /**
     * Method to get a model object, loading it if required.
     *
     * @param   string  $name    The model name. Optional.
     * @param   string  $prefix  The class prefix. Optional.
     * @param   array   $config  Configuration array for model. Optional.
     *
     * @return  JModelLegacy  The model.
     *
     * @since   1.6
     */
    public function getModel($name = 'Beer', $prefix = 'BeersModel', $config = array('ignore_request' => true))
    {
        \Joomla\CMS\MVC\Model\BaseDatabaseModel::addIncludePath('/administrator/components/com_beers/models');

        return parent::getModel($name, $prefix, $config);
    }

	public function delete()
	{
		parent::delete(); // TODO: Change the autogenerated stub
	}

	public function import()
    {
        /** @var BeersModelBeers $model */
        $model = $this->getModel('Beers');
        $model->import();

        \Joomla\CMS\Factory::getApplication()->enqueueMessage('Successfully imported beers');
        \Joomla\CMS\Factory::getApplication()->redirect('index.php?option=com_beers&view=beers');
    }

//    public function publish($cid)
//    {
//        if ($cid)
//        {
//            $client = $this->getClient();
//
//            $params = JComponentHelper::getParams('com_languages');
//            $params->set($client->name, $cid);
//
//            $table = JTable::getInstance('extension');
//            $id    = $table->find(array('element' => 'com_languages'));
//
//            // Load.
//            if (!$table->load($id))
//            {
//                $this->setError($table->getError());
//
//                return false;
//            }
//
//            $table->params = (string) $params;
//
//            // Pre-save checks.
//            if (!$table->check())
//            {
//                $this->setError($table->getError());
//
//                return false;
//            }
//
//            // Save the changes.
//            if (!$table->store())
//            {
//                $this->setError($table->getError());
//
//                return false;
//            }
//        }
//        else
//        {
//            $this->setError(JText::_('COM_LANGUAGES_ERR_NO_LANGUAGE_SELECTED'));
//
//            return false;
//        }
//
//        // Clean the cache of com_languages and component cache.
//        $this->cleanCache();
//        $this->cleanCache('_system', 0);
//        $this->cleanCache('_system', 1);
//
//        return true;
//    }
}
